#Version Number
build: 20191224

# Site settings
title: Cat and Kevin
subtitle: "Catherine and Kevin's wedding website"
url: "https://catgoesmiu.com" # the base hostname & protocol for your site
# baseurl: "/the/subpath/of/your/site" # Set this value to "" if you want your site to be root
baseurl: ""


# Bridal Party Names
bridesmaids_0:
- name: Risa
  pic: risa
  position: Matron of Honor

bridesmaids_1:
- name: Kristine
  pic: kristine
  position: Bridesmaid

- name: Kristin
  pic: kristin
  position: Bridesmaid

- name: Emily
  pic: emily
  position: Bridesmaid

- name: Renee
  pic: renee
  position: Bridesmaid

groomsmen_0:
- name: Keith
  pic: keith
  position: Best Man and Brother of the Groom

groomsmen_1:
- name: Andrew
  pic: andrew
  position: Groomsman

- name: Binh
  pic: binh
  position: Groomsman

- name: Tjuan
  pic: tjuan
  position: Groomsman

- name: Calvin
  pic: calvin
  position: Groomsman and Brother of the Bride


# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/jekyllrb
  - title: facebook
    url:
  - title: stack-overflow
    url: http://stackoverflow.com/questions/tagged/jekyll
  - title: bitbucket
    url: http://bitbucket.org/jekyll
  - title: github
    url: http://github.com/jekyll

# Postal address (add as many lines as necessary)
address:
  - line: 3481 Melrose Place
  - line: Beverly Hills, CA 90210

# Build settings
markdown: kramdown
permalink: pretty
